In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [ ]:
# URL of the dataset
dataset_url = "http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data_10_percent.gz" # 10% of the dataset
# dataset_url  = "http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data.gz" # Full dataset

In [ ]:
# URL of the dataset
url = "http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data_10_percent.gz"
# url = "http://kdd.ics.uci.edu/databases/kddcup99/kddcup.data.gz"

# 41 Features + 1 attack type
feature_names = [
    "duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", "land", "wrong_fragment", "urgent",
    "hot", "num_failed_logins", "logged_in", "num_compromised", "root_shell", "su_attempted", "num_root",
    "num_file_creations", "num_shells", "num_access_files", "num_outbound_cmds", "is_host_login", "is_guest_login",
    "count", "srv_count", "serror_rate", "srv_serror_rate", "rerror_rate", "srv_rerror_rate", "same_srv_rate",
    "diff_srv_rate", "srv_diff_host_rate", "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate",
    "dst_host_diff_srv_rate", "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate", "dst_host_serror_rate",
    "dst_host_srv_serror_rate", "dst_host_rerror_rate", "dst_host_srv_rerror_rate", "attack_type"
]

In [ ]:
# Load the dataset
data = pd.read_csv(url, names=feature_names, header=None)

# Drop categorical features
categorical_features = ["protocol_type", "service", "flag"]
data = data.drop(columns=categorical_features)

# Mark 'attack_type' as binary: 0 for "normal.", 1 for any attack
data["attack_type"] = data["attack_type"].apply(lambda x: 0 if x == "normal." else 1)

# Display the first few rows of the processed dataset
data

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type
0,0,181,5450,0,0,0,0,0,1,0,...,9,1.0,0.0,0.11,0.00,0.00,0.00,0.0,0.0,0
1,0,239,486,0,0,0,0,0,1,0,...,19,1.0,0.0,0.05,0.00,0.00,0.00,0.0,0.0,0
2,0,235,1337,0,0,0,0,0,1,0,...,29,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,0
3,0,219,1337,0,0,0,0,0,1,0,...,39,1.0,0.0,0.03,0.00,0.00,0.00,0.0,0.0,0
4,0,217,2032,0,0,0,0,0,1,0,...,49,1.0,0.0,0.02,0.00,0.00,0.00,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494016,0,310,1881,0,0,0,0,0,1,0,...,255,1.0,0.0,0.01,0.05,0.00,0.01,0.0,0.0,0
494017,0,282,2286,0,0,0,0,0,1,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,0
494018,0,203,1200,0,0,0,0,0,1,0,...,255,1.0,0.0,0.06,0.05,0.06,0.01,0.0,0.0,0
494019,0,291,1200,0,0,0,0,0,1,0,...,255,1.0,0.0,0.04,0.05,0.04,0.01,0.0,0.0,0
494020,0,219,1234,0,0,0,0,0,1,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,0

In [ ]:
# Display basic info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494021 entries, 0 to 494020
Data columns (total 39 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     494021 non-null  int64
 1   src_bytes                    494021 non-null  int64
 2   dst_bytes                    494021 non-null  int64
 3   land                         494021 non-null  int64
 4   wrong_fragment               494021 non-null  int64
 5   urgent                       494021 non-null  int64
 6   hot                          494021 non-null  int64
 7   num_failed_logins            494021 non-null  int64
 8   logged_in                    494021 non-null  int64
 9   num_compromised              494021 non-null  int64
 10  root_shell                   494021 non-null  int64
 11  su_attempted                 494021 non-null  int64
 12  num_root                     494021 non-null  int64
 13  num_file_creations           494021 non-null  int64
 14  num_shells                   494021 non-null  int64
 15  num_access_files             494021 non-null  int64
 16  num_outbound_cmds            494021 non-null  int64
 17  is_host_login                494021 non-null  int64
 18  is_guest_login               494021 non-null  int64
 19  count                        494021 non-null  int64
 20  srv_count                    494021 non-null  int64
 21  serror_rate                  494021 non-null  float64
 22  srv_serror_rate              494021 non-null  float64
 23  rerror_rate                  494021 non-null  float64
 24  srv_rerror_rate              494021 non-null  float64
 25  same_srv_rate                494021 non-null  float64
 26  diff_srv_rate                494021 non-null  float64
 27  srv_diff_host_rate           494021 non-null  float64
 28  dst_host_count               494021 non-null  int64
 29  dst_host_srv_count           494021 non-null  int64
 30  dst_host_same_srv_rate       494021 non-null  float64
 31  dst_host_diff_srv_rate       494021 non-null  float64
 32  dst_host_same_src_port_rate  494021 non-null  float64
 33  dst_host_srv_diff_host_rate  494021 non-null  float64
 34  dst_host_serror_rate         494021 non-null  float64
 35  dst_host_srv_serror_rate     494021 non-null  float64
 36  dst_host_rerror_rate         494021 non-null  float64
 37  dst_host_srv_rerror_rate     494021 non-null  float64
 38  attack_type                  494021 non-null  int64
dtypes: float64(15), int64(24)
memory usage: 147.0 MB

In [ ]:
# Display summary statistics
data.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type
count,494021.000000,4.940210e+05,4.940210e+05,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,...,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000,494021.000000
mean,47.979302,3.025610e+03,8.685324e+02,0.000045,0.006433,0.000014,0.034519,0.000152,0.148247,0.010212,...,188.665670,0.753780,0.030906,0.601935,0.006684,0.176754,0.176443,0.058118,0.057412,0.803089
std,707.746472,9.882181e+05,3.304000e+04,0.006673,0.134805,0.005510,0.782103,0.015520,0.355345,1.798326,...,106.040437,0.410781,0.109259,0.481309,0.042133,0.380593,0.380919,0.230590,0.230140,0.397665
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,4.500000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,46.000000,0.410000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,5.200000e+02,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,0.000000,1.032000e+03,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,1.000000,0.040000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,58329.000000,6.933756e+08,5.155468e+06,1.000000,3.000000,3.000000,30.000000,5.000000,1.000000,884.000000,...,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# Standardization of Non-Binary Features
# Identify Non-Binary Features
binary_features = ['land', 'logged_in', 'root_shell','su_attempted', 'is_host_login', 'is_guest_login', 'attack_type']
non_binary_features = [col for col in data.columns if col not in binary_features]

# Standardize Non-Binary Features (excluding 'attack_type')
scaler = StandardScaler()
balanced_data = data
balanced_data[non_binary_features] = scaler.fit_transform(balanced_data[non_binary_features])

print(len(balanced_data))

494021

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Step 1: Split the data into features and target
X = balanced_data.drop('attack_type', axis=1)  # Features (all columns except the target)
y = balanced_data['attack_type']  # Target variable (attack_type)

# Step 2: Split the data into training and testing sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Initialize and train the Logistic Regression model
logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train, y_train)

# Step 4: Make predictions on the training and test data
y_train_pred = logreg.predict(X_train)
y_test_pred = logreg.predict(X_test)

# Step 5: Evaluate the model on the training and test sets
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Training Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

# Classification Report for Training Data
print("\nClassification Report (Training Data):")
print(classification_report(y_train, y_train_pred))

# Classification Report for Testing Data
print("\nClassification Report (Testing Data):")
print(classification_report(y_test, y_test_pred))

# Confusion Matrix for Testing Data
print("\nConfusion Matrix (Testing Data):")
print(confusion_matrix(y_test, y_test_pred))

Training Accuracy: 0.9966
Test Accuracy: 0.9964

Classification Report (Training Data):
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     77925
           1       1.00      1.00      1.00    317291

    accuracy                           1.00    395216
   macro avg       0.99      1.00      0.99    395216
weighted avg       1.00      1.00      1.00    395216


Classification Report (Testing Data):
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     19353
           1       1.00      1.00      1.00     79452

    accuracy                           1.00     98805
   macro avg       0.99      1.00      0.99     98805
weighted avg       1.00      1.00      1.00     98805


Confusion Matrix (Testing Data):
[[19222   131]
 [  227 79225]]

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Step 1: Split the data into features and target
X = balanced_data.drop('attack_type', axis=1)  # Features (all columns except the target)
y = balanced_data['attack_type']  # Target variable (attack_type)

# Step 2: Split the data into training and testing sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Initialize and train the XGBoost model
xgboost_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgboost_model.fit(X_train, y_train)

# Step 4: Make predictions on the training and test data
y_train_pred = xgboost_model.predict(X_train)
y_test_pred = xgboost_model.predict(X_test)

# Step 5: Evaluate the model on the training and test sets
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Training Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

# Classification Report for Training Data
print("\nClassification Report (Training Data):")
print(classification_report(y_train, y_train_pred))

# Classification Report for Testing Data
print("\nClassification Report (Testing Data):")
print(classification_report(y_test, y_test_pred))

# Confusion Matrix for Testing Data
print("\nConfusion Matrix (Testing Data):")
print(confusion_matrix(y_test, y_test_pred))

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [07:03:29] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Training Accuracy: 1.0000
Test Accuracy: 0.9999

Classification Report (Training Data):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     77925
           1       1.00      1.00      1.00    317291

    accuracy                           1.00    395216
   macro avg       1.00      1.00      1.00    395216
weighted avg       1.00      1.00      1.00    395216


Classification Report (Testing Data):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19353
           1       1.00      1.00      1.00     79452

    accuracy                           1.00     98805
   macro avg       1.00      1.00      1.00     98805
weighted avg       1.00      1.00      1.00     98805


Confusion Matrix (Testing Data):
[[19346     7]
 [    7 79445]]

In [ ]:
from sklearn.decomposition import TruncatedSVD

# Assuming df_cleaned is your preprocessed DataFrame
# Select numerical features for CUR decomposition
numerical_cols = balanced_data.select_dtypes(include=['number']).columns
numerical_data = balanced_data[numerical_cols]

# Apply CUR decomposition
n_components = 10
svd = TruncatedSVD(n_components=n_components, random_state=42)
svd.fit(numerical_data)

# Extract C, U, and R matrices
C = svd.components_.T  # Column matrix
U = np.diag(svd.singular_values_)  # Diagonal matrix of singular values
R = svd.components_  # Row matrix

print("C matrix shape:", C.shape)
print("U matrix shape:", U.shape)
print("R matrix shape:", R.shape)

C matrix shape: (39, 10)
U matrix shape: (10, 10)
R matrix shape: (10, 39)

In [ ]:
from sklearn.decomposition import PCA

# Step 1: Split the data into features and target
X = balanced_data.drop('attack_type', axis=1)  # Features (all columns except the target)
y = balanced_data['attack_type']  # Target variable (attack_type)

# Step 2: Apply PCA to reduce to 10 components
pca = PCA(n_components=10)
X_pca = pca.fit_transform(X)

# Step 3: Split the PCA-transformed data into training and testing sets (80-20 split)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

In [ ]:
# Step 4: Logistic Regression Model
logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train, y_train)

# Step 5: Make predictions with Logistic Regression
y_train_pred_logreg = logreg.predict(X_train)
y_test_pred_logreg = logreg.predict(X_test)

# Step 6: Evaluate Logistic Regression Model
train_accuracy_logreg = accuracy_score(y_train, y_train_pred_logreg)
test_accuracy_logreg = accuracy_score(y_test, y_test_pred_logreg)

print(f"Logistic Regression - Training Accuracy: {train_accuracy_logreg:.4f}")
print(f"Logistic Regression - Test Accuracy: {test_accuracy_logreg:.4f}")
print("\nLogistic Regression - Classification Report (Test Data):")
print(classification_report(y_test, y_test_pred_logreg))

# Confusion Matrix for Logistic Regression
print("\nLogistic Regression - Confusion Matrix (Test Data):")
print(confusion_matrix(y_test, y_test_pred_logreg))

Logistic Regression - Training Accuracy: 0.9852
Logistic Regression - Test Accuracy: 0.9843

Logistic Regression - Classification Report (Test Data):
              precision    recall  f1-score   support

           0       0.95      0.97      0.96     19353
           1       0.99      0.99      0.99     79452

    accuracy                           0.98     98805
   macro avg       0.97      0.98      0.98     98805
weighted avg       0.98      0.98      0.98     98805


Logistic Regression - Confusion Matrix (Test Data):
[[18863   490]
 [ 1062 78390]]

In [ ]:
import xgboost as xgb

# Step 7: XGBoost Model
xgboost_model = xgb.XGBClassifier(eval_metric='logloss', random_state=42)
xgboost_model.fit(X_train, y_train)

# Step 8: Make predictions with XGBoost
y_train_pred_xgb = xgboost_model.predict(X_train)
y_test_pred_xgb = xgboost_model.predict(X_test)

# Step 9: Evaluate XGBoost Model
train_accuracy_xgb = accuracy_score(y_train, y_train_pred_xgb)
test_accuracy_xgb = accuracy_score(y_test, y_test_pred_xgb)

print(f"\nXGBoost - Training Accuracy: {train_accuracy_xgb:.4f}")
print(f"XGBoost - Test Accuracy: {test_accuracy_xgb:.4f}")
print("\nXGBoost - Classification Report (Test Data):")
print(classification_report(y_test, y_test_pred_xgb))

# Confusion Matrix for XGBoost
print("\nXGBoost - Confusion Matrix (Test Data):")
print(confusion_matrix(y_test, y_test_pred_xgb))

XGBoost - Training Accuracy: 0.9998
XGBoost - Test Accuracy: 0.9993

XGBoost - Classification Report (Test Data):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19353
           1       1.00      1.00      1.00     79452

    accuracy                           1.00     98805
   macro avg       1.00      1.00      1.00     98805
weighted avg       1.00      1.00      1.00     98805


XGBoost - Confusion Matrix (Test Data):
[[19322    31]
 [   43 79409]]

In [ ]:
from sklearn.random_projection import GaussianRandomProjection
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb

# Regular JL Lemma (GaussianRandomProjection)
regular_jl = GaussianRandomProjection(n_components=10, random_state=42)
X_regular_jl = regular_jl.fit_transform(X)

# Split the transformed data into training and test sets
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_regular_jl, y, test_size=0.2, random_state=42)

# Logistic Regression
logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train_reg, y_train_reg)
y_train_pred_logreg = logreg.predict(X_train_reg)
y_test_pred_logreg = logreg.predict(X_test_reg)

# Results for Logistic Regression
train_accuracy_logreg = accuracy_score(y_train_reg, y_train_pred_logreg)
test_accuracy_logreg = accuracy_score(y_test_reg, y_test_pred_logreg)
print(f"Logistic Regression (Regular JL) - Training Accuracy: {train_accuracy_logreg:.4f}")
print(f"Logistic Regression (Regular JL) - Test Accuracy: {test_accuracy_logreg:.4f}")
print("\nLogistic Regression (Regular JL) - Classification Report (Test Data):")
print(classification_report(y_test_reg, y_test_pred_logreg))

# XGBoost
xgboost_model = xgb.XGBClassifier(eval_metric='logloss', random_state=42)
xgboost_model.fit(X_train_reg, y_train_reg)
y_train_pred_xgb = xgboost_model.predict(X_train_reg)
y_test_pred_xgb = xgboost_model.predict(X_test_reg)

# Results for XGBoost
train_accuracy_xgb = accuracy_score(y_train_reg, y_train_pred_xgb)
test_accuracy_xgb = accuracy_score(y_test_reg, y_test_pred_xgb)
print(f"\nXGBoost (Regular JL) - Training Accuracy: {train_accuracy_xgb:.4f}")
print(f"XGBoost (Regular JL) - Test Accuracy: {test_accuracy_xgb:.4f}")
print("\nXGBoost (Regular JL) - Classification Report (Test Data):")
print(classification_report(y_test_reg, y_test_pred_xgb))

Logistic Regression (Regular JL) - Training Accuracy: 0.9846
Logistic Regression (Regular JL) - Test Accuracy: 0.9843

Logistic Regression (Regular JL) - Classification Report (Test Data):
              precision    recall  f1-score   support

           0       0.94      0.98      0.96     19353
           1       0.99      0.99      0.99     79452

    accuracy                           0.98     98805
   macro avg       0.97      0.98      0.98     98805
weighted avg       0.98      0.98      0.98     98805


XGBoost (Regular JL) - Training Accuracy: 0.9997
XGBoost (Regular JL) - Test Accuracy: 0.9991

XGBoost (Regular JL) - Classification Report (Test Data):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19353
           1       1.00      1.00      1.00     79452

    accuracy                           1.00     98805
   macro avg       1.00      1.00      1.00     98805
weighted avg       1.00      1.00      1.00     98805

In [ ]:
from sklearn.random_projection import SparseRandomProjection

# Sparse JL Lemma (SparseRandomProjection)
sparse_jl = SparseRandomProjection(n_components=10, random_state=42)
X_sparse_jl = sparse_jl.fit_transform(X)

# Split the transformed data into training and test sets
X_train_sparse, X_test_sparse, y_train_sparse, y_test_sparse = train_test_split(X_sparse_jl, y, test_size=0.2, random_state=42)

# Logistic Regression
logreg.fit(X_train_sparse, y_train_sparse)
y_train_pred_logreg = logreg.predict(X_train_sparse)
y_test_pred_logreg = logreg.predict(X_test_sparse)

# Results for Logistic Regression
train_accuracy_logreg = accuracy_score(y_train_sparse, y_train_pred_logreg)
test_accuracy_logreg = accuracy_score(y_test_sparse, y_test_pred_logreg)
print(f"Logistic Regression (Sparse JL) - Training Accuracy: {train_accuracy_logreg:.4f}")
print(f"Logistic Regression (Sparse JL) - Test Accuracy: {test_accuracy_logreg:.4f}")
print("\nLogistic Regression (Sparse JL) - Classification Report (Test Data):")
print(classification_report(y_test_sparse, y_test_pred_logreg))

# XGBoost
xgboost_model.fit(X_train_sparse, y_train_sparse)
y_train_pred_xgb = xgboost_model.predict(X_train_sparse)
y_test_pred_xgb = xgboost_model.predict(X_test_sparse)

# Results for XGBoost
train_accuracy_xgb = accuracy_score(y_train_sparse, y_train_pred_xgb)
test_accuracy_xgb = accuracy_score(y_test_sparse, y_test_pred_xgb)
print(f"\nXGBoost (Sparse JL) - Training Accuracy: {train_accuracy_xgb:.4f}")
print(f"XGBoost (Sparse JL) - Test Accuracy: {test_accuracy_xgb:.4f}")
print("\nXGBoost (Sparse JL) - Classification Report (Test Data):")
print(classification_report(y_test_sparse, y_test_pred_xgb))

Logistic Regression (Sparse JL) - Training Accuracy: 0.9777
Logistic Regression (Sparse JL) - Test Accuracy: 0.9779

Logistic Regression (Sparse JL) - Classification Report (Test Data):
              precision    recall  f1-score   support

           0       0.96      0.93      0.94     19353
           1       0.98      0.99      0.99     79452

    accuracy                           0.98     98805
   macro avg       0.97      0.96      0.96     98805
weighted avg       0.98      0.98      0.98     98805


XGBoost (Sparse JL) - Training Accuracy: 1.0000
XGBoost (Sparse JL) - Test Accuracy: 0.9997

XGBoost (Sparse JL) - Classification Report (Test Data):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19353
           1       1.00      1.00      1.00     79452

    accuracy                           1.00     98805
   macro avg       1.00      1.00      1.00     98805
weighted avg       1.00      1.00      1.00     98805